name: Build and deploy ASP.Net Core app to Azure Web App - contract-auction-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Replace strings in appsettings.json
        env:
          MFL_API_KEY_15238: ${{ secrets.MFL_API_KEY_15238 }}
          MFL_API_KEY_26548: ${{ secrets.MFL_API_KEY_26548 }}
        run: |
          # Define the path to your appsettings.json file
          $appSettingsPath = "${{ github.workspace }}\FreeAgencyAuctionAPI\appsettings.json"
          
          # Read the file contents
          $json = Get-Content $appSettingsPath | Out-String | ConvertFrom-Json
          
          # Update the JSON properties with secrets
          $json.Mfl.MflApiKey[0].key = $env:MFL_API_KEY_15238
          $json.Mfl.MflApiKey[1].key = $env:MFL_API_KEY_26548
          
          # Save the updated JSON back to the file
          $json | ConvertTo-Json -Depth 10 | Set-Content $appSettingsPath
          
          # Optional: Output the updated appsettings.json for verification
          Get-Content $appSettingsPath

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'contract-auction-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_43A3A11CB193494181D0E51B0B857AD1 }}
          package: .