# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - contract-auction-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Install jq
        run: choco install jq -y
      - name: Replace strings in appsettings.json
        env:
          COMMISH_COOKIE: ${{ secrets.COMMISH_COOKIE }}
          MFL_API_KEY_15238: ${{ secrets.MFL_API_KEY_15238 }}
          MFL_API_KEY_26548: ${{ secrets.MFL_API_KEY_26548 }}
        run: |
          # Define the path to your appsettings.Development.json file
          $appSettingsPath = "${{ github.workspace }}\FreeAgencyAuctionAPI\appsettings.Development.json"
          
          # Update the MflApiKey with the respective keys from secrets
          jq --arg key1 "$env:MFL_API_KEY_15238" '.Mfl.MflApiKey[0].key = $key1' $appSettingsPath | Out-File -Encoding utf8 $appSettingsPath
          jq --arg key2 "$env:MFL_API_KEY_26548" '.Mfl.MflApiKey[1].key = $key2' $appSettingsPath | Out-File -Encoding utf8 $appSettingsPath

          # Output the updated appsettings.json (optional for logging)
          Get-Content $appSettingsPath
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'contract-auction-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_43A3A11CB193494181D0E51B0B857AD1 }}
          package: .
